language: node_js
node_js: stable
cache:
  directories:
  - bower_components
branches:
  only:
    - master
before_script:
- npm install -g bower polylint
- bower prune
- bower install
script:
- polylint
